export enum EventCategoryId {
  Drought = 'drought',
  DustHaze = 'dustHaze',
  Earthquakes = 'earthquakes',
  Floods = 'floods',
  Landslides = 'landslides',
  Manmade = 'manmade',
  SeaLakeIce = 'seaLakeIce',
  SevereStorms = 'severeStorms',
  Snow = 'snow',
  TempExtremes = 'tempExtremes',
  Volcanoes = 'volcanoes',
  WaterColor = 'waterColor',
  Wildfires = 'wildfires',
}
